-- MySQL Script generated by MySQL Workbench
-- Sat Aug 30 16:29:02 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema pi_bbd
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema pi_bbd
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `pi_bbd` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `pi_bbd` ;

-- -----------------------------------------------------
-- Table `pi_bbd`.`localizacao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pi_bbd`.`localizacao` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `cidade` VARCHAR(255) NULL DEFAULT NULL,
  `estado` VARCHAR(255) NULL DEFAULT NULL,
  `pais` VARCHAR(255) NULL DEFAULT NULL,
  `latitude` DOUBLE NULL DEFAULT NULL,
  `longitude` DOUBLE NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `pi_bbd`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pi_bbd`.`usuario` (
  `CPF` VARCHAR(14) NOT NULL,
  `nome` VARCHAR(255) NOT NULL,
  `telefone` VARCHAR(20) NULL DEFAULT NULL,
  `email` VARCHAR(255) NOT NULL,
  `senha` VARCHAR(255) NOT NULL,
  `bio` TEXT NULL DEFAULT NULL,
  `fotoDePerfil` VARCHAR(255) NULL DEFAULT NULL,
  `localizacaoAtual_id` INT NULL DEFAULT NULL,
  PRIMARY KEY (`CPF`),
  UNIQUE INDEX `email` (`email` ASC) VISIBLE,
  INDEX `localizacaoAtual_id` (`localizacaoAtual_id` ASC) VISIBLE,
  CONSTRAINT `usuario_ibfk_1`
    FOREIGN KEY (`localizacaoAtual_id`)
    REFERENCES `pi_bbd`.`localizacao` (`id`)
    ON DELETE SET NULL)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `pi_bbd`.`clube`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pi_bbd`.`clube` (
  `IDclube` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`IDclube`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `pi_bbd`.`administrador`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pi_bbd`.`administrador` (
  `CPF` VARCHAR(14) NOT NULL,
  `IDadm` INT NOT NULL AUTO_INCREMENT,
  `clube_IDclube` INT NOT NULL,
  PRIMARY KEY (`CPF`),
  UNIQUE INDEX `IDadm` (`IDadm` ASC) VISIBLE,
  INDEX `fk_administrador_clube1_idx` (`clube_IDclube` ASC) VISIBLE,
  CONSTRAINT `administrador_ibfk_1`
    FOREIGN KEY (`CPF`)
    REFERENCES `pi_bbd`.`usuario` (`CPF`)
    ON DELETE CASCADE,
  CONSTRAINT `fk_administrador_clube1`
    FOREIGN KEY (`clube_IDclube`)
    REFERENCES `pi_bbd`.`clube` (`IDclube`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `pi_bbd`.`atleta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pi_bbd`.`atleta` (
  `CPF` VARCHAR(14) NOT NULL,
  `IDatleta` INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`CPF`),
  UNIQUE INDEX `IDatleta` (`IDatleta` ASC) VISIBLE,
  CONSTRAINT `atleta_ibfk_1`
    FOREIGN KEY (`CPF`)
    REFERENCES `pi_bbd`.`usuario` (`CPF`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `pi_bbd`.`esporte`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pi_bbd`.`esporte` (
  `nome` VARCHAR(255) NOT NULL,
  `IDesporte` INT NOT NULL AUTO_INCREMENT,
  `categoria` ENUM('Individual', 'Coletivo') NULL DEFAULT NULL,
  PRIMARY KEY (`nome`),
  UNIQUE INDEX `IDesporte` (`IDesporte` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `pi_bbd`.`clube_esportes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pi_bbd`.`clube_esportes` (
  `IDclube` INT NOT NULL,
  `nome_esporte` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`IDclube`, `nome_esporte`),
  INDEX `nome_esporte` (`nome_esporte` ASC) VISIBLE,
  CONSTRAINT `clube_esportes_ibfk_1`
    FOREIGN KEY (`IDclube`)
    REFERENCES `pi_bbd`.`clube` (`IDclube`)
    ON DELETE CASCADE,
  CONSTRAINT `clube_esportes_ibfk_2`
    FOREIGN KEY (`nome_esporte`)
    REFERENCES `pi_bbd`.`esporte` (`nome`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `pi_bbd`.`publicacao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pi_bbd`.`publicacao` (
  `IDpublicacao` INT NOT NULL AUTO_INCREMENT,
  `data_publicacao` DATE NULL DEFAULT NULL,
  `conteudo` TEXT NULL DEFAULT NULL,
  `autor_CPF` VARCHAR(14) NOT NULL,
  PRIMARY KEY (`IDpublicacao`),
  INDEX `autor_CPF` (`autor_CPF` ASC) VISIBLE,
  CONSTRAINT `publicacao_ibfk_1`
    FOREIGN KEY (`autor_CPF`)
    REFERENCES `pi_bbd`.`usuario` (`CPF`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `pi_bbd`.`comentario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pi_bbd`.`comentario` (
  `IDcomentario` INT NOT NULL AUTO_INCREMENT,
  `conteudo` TEXT NULL DEFAULT NULL,
  `horario` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `autor_CPF` VARCHAR(14) NOT NULL,
  `IDpublicacao` INT NOT NULL,
  PRIMARY KEY (`IDcomentario`),
  INDEX `autor_CPF` (`autor_CPF` ASC) VISIBLE,
  INDEX `IDpublicacao` (`IDpublicacao` ASC) VISIBLE,
  CONSTRAINT `comentario_ibfk_1`
    FOREIGN KEY (`autor_CPF`)
    REFERENCES `pi_bbd`.`usuario` (`CPF`)
    ON DELETE CASCADE,
  CONSTRAINT `comentario_ibfk_2`
    FOREIGN KEY (`IDpublicacao`)
    REFERENCES `pi_bbd`.`publicacao` (`IDpublicacao`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `pi_bbd`.`conquista`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pi_bbd`.`conquista` (
  `IDconquista` INT NOT NULL AUTO_INCREMENT,
  `titulo` VARCHAR(255) NOT NULL,
  `descricao` TEXT NULL DEFAULT NULL,
  `data_conquista` DATE NULL DEFAULT NULL,
  `conquistado_por` VARCHAR(14) NULL DEFAULT NULL,
  PRIMARY KEY (`IDconquista`),
  INDEX `conquistado_por` (`conquistado_por` ASC) VISIBLE,
  CONSTRAINT `conquista_ibfk_1`
    FOREIGN KEY (`conquistado_por`)
    REFERENCES `pi_bbd`.`atleta` (`CPF`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `pi_bbd`.`denuncia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pi_bbd`.`denuncia` (
  `IDdenuncia` INT NOT NULL AUTO_INCREMENT,
  `data_denuncia` DATE NULL DEFAULT NULL,
  `conteudo` TEXT NULL DEFAULT NULL,
  `denunciante_CPF` VARCHAR(14) NULL DEFAULT NULL,
  `denunciado_CPF` VARCHAR(14) NULL DEFAULT NULL,
  PRIMARY KEY (`IDdenuncia`),
  INDEX `denunciante_CPF` (`denunciante_CPF` ASC) VISIBLE,
  INDEX `denunciado_CPF` (`denunciado_CPF` ASC) VISIBLE,
  CONSTRAINT `denuncia_ibfk_1`
    FOREIGN KEY (`denunciante_CPF`)
    REFERENCES `pi_bbd`.`usuario` (`CPF`)
    ON DELETE SET NULL,
  CONSTRAINT `denuncia_ibfk_2`
    FOREIGN KEY (`denunciado_CPF`)
    REFERENCES `pi_bbd`.`usuario` (`CPF`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `pi_bbd`.`evento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pi_bbd`.`evento` (
  `IDevento` INT NOT NULL AUTO_INCREMENT,
  `titulo` VARCHAR(255) NOT NULL,
  `requisito` TEXT NULL DEFAULT NULL,
  `descricao` TEXT NULL DEFAULT NULL,
  `horario` DATETIME NULL DEFAULT NULL,
  `data_evento` DATE NULL DEFAULT NULL,
  PRIMARY KEY (`IDevento`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `pi_bbd`.`evento_convidados`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pi_bbd`.`evento_convidados` (
  `IDevento` INT NOT NULL,
  `CPF_convidado` VARCHAR(14) NOT NULL,
  `Convidado` TINYINT NULL,
  `Confirmado` TINYINT NULL,
  `participou` TINYINT NULL,
  PRIMARY KEY (`IDevento`, `CPF_convidado`),
  INDEX `CPF_convidado` (`CPF_convidado` ASC) VISIBLE,
  CONSTRAINT `evento_convidados_ibfk_1`
    FOREIGN KEY (`IDevento`)
    REFERENCES `pi_bbd`.`evento` (`IDevento`)
    ON DELETE CASCADE,
  CONSTRAINT `evento_convidados_ibfk_2`
    FOREIGN KEY (`CPF_convidado`)
    REFERENCES `pi_bbd`.`usuario` (`CPF`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `pi_bbd`.`grupo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pi_bbd`.`grupo` (
  `IDgrupo` INT NOT NULL AUTO_INCREMENT,
  `titulo` VARCHAR(255) NOT NULL,
  `descricao` TEXT NULL DEFAULT NULL,
  `esporte_grupo` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`IDgrupo`),
  INDEX `esporte_grupo` (`esporte_grupo` ASC) VISIBLE,
  CONSTRAINT `grupo_ibfk_1`
    FOREIGN KEY (`esporte_grupo`)
    REFERENCES `pi_bbd`.`esporte` (`nome`)
    ON DELETE SET NULL)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `pi_bbd`.`grupo_membros`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pi_bbd`.`grupo_membros` (
  `IDgrupo` INT NOT NULL,
  `CPF_membro` VARCHAR(14) NOT NULL,
  PRIMARY KEY (`IDgrupo`, `CPF_membro`),
  INDEX `CPF_membro` (`CPF_membro` ASC) VISIBLE,
  CONSTRAINT `grupo_membros_ibfk_1`
    FOREIGN KEY (`IDgrupo`)
    REFERENCES `pi_bbd`.`grupo` (`IDgrupo`)
    ON DELETE CASCADE,
  CONSTRAINT `grupo_membros_ibfk_2`
    FOREIGN KEY (`CPF_membro`)
    REFERENCES `pi_bbd`.`usuario` (`CPF`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `pi_bbd`.`mensagem`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pi_bbd`.`mensagem` (
  `IDmensagem` INT NOT NULL AUTO_INCREMENT,
  `conteudo` TEXT NULL DEFAULT NULL,
  `horario_data` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `destinatario_CPF` VARCHAR(14) NULL DEFAULT NULL,
  `grupo_IDgrupo` INT NULL,
  `remetente_CPF` VARCHAR(14) NOT NULL,
  PRIMARY KEY (`IDmensagem`),
  INDEX `destinatario_CPF` (`destinatario_CPF` ASC) VISIBLE,
  INDEX `fk_mensagem_grupo1_idx` (`grupo_IDgrupo` ASC) VISIBLE,
  INDEX `fk_mensagem_usuario1_idx` (`remetente_CPF` ASC) VISIBLE,
  CONSTRAINT `mensagem_ibfk_2`
    FOREIGN KEY (`destinatario_CPF`)
    REFERENCES `pi_bbd`.`usuario` (`CPF`)
    ON DELETE SET NULL,
  CONSTRAINT `fk_mensagem_grupo1`
    FOREIGN KEY (`grupo_IDgrupo`)
    REFERENCES `pi_bbd`.`grupo` (`IDgrupo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_mensagem_usuario1`
    FOREIGN KEY (`remetente_CPF`)
    REFERENCES `pi_bbd`.`usuario` (`CPF`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `pi_bbd`.`notificacao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pi_bbd`.`notificacao` (
  `IDnotificacao` INT NOT NULL AUTO_INCREMENT,
  `titulo` VARCHAR(255) NOT NULL,
  `conteudo` TEXT NULL DEFAULT NULL,
  `remetente_CPF` VARCHAR(14) NULL DEFAULT NULL,
  `destinatario_CPF` VARCHAR(14) NULL DEFAULT NULL,
  `horario` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `data_leitura` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`IDnotificacao`),
  INDEX `remetente_CPF` (`remetente_CPF` ASC) VISIBLE,
  INDEX `destinatario_CPF` (`destinatario_CPF` ASC) VISIBLE,
  CONSTRAINT `notificacao_ibfk_1`
    FOREIGN KEY (`remetente_CPF`)
    REFERENCES `pi_bbd`.`usuario` (`CPF`)
    ON DELETE SET NULL,
  CONSTRAINT `notificacao_ibfk_2`
    FOREIGN KEY (`destinatario_CPF`)
    REFERENCES `pi_bbd`.`usuario` (`CPF`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `pi_bbd`.`professor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pi_bbd`.`professor` (
  `CPF` VARCHAR(14) NOT NULL,
  `IDprofessor` INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`CPF`),
  UNIQUE INDEX `IDprofessor` (`IDprofessor` ASC) VISIBLE,
  CONSTRAINT `professor_ibfk_1`
    FOREIGN KEY (`CPF`)
    REFERENCES `pi_bbd`.`usuario` (`CPF`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `pi_bbd`.`seguidores`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pi_bbd`.`seguidores` (
  `CPF_seguidor` VARCHAR(14) NOT NULL,
  `CPF_seguido` VARCHAR(14) NOT NULL,
  PRIMARY KEY (`CPF_seguidor`, `CPF_seguido`),
  INDEX `CPF_seguido` (`CPF_seguido` ASC) VISIBLE,
  CONSTRAINT `seguidores_ibfk_1`
    FOREIGN KEY (`CPF_seguidor`)
    REFERENCES `pi_bbd`.`usuario` (`CPF`)
    ON DELETE CASCADE,
  CONSTRAINT `seguidores_ibfk_2`
    FOREIGN KEY (`CPF_seguido`)
    REFERENCES `pi_bbd`.`usuario` (`CPF`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `pi_bbd`.`usuario_esportesdeinteresse`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pi_bbd`.`usuario_esportesdeinteresse` (
  `CPF_usuario` VARCHAR(14) NOT NULL,
  `nome_esporte` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`CPF_usuario`, `nome_esporte`),
  INDEX `nome_esporte` (`nome_esporte` ASC) VISIBLE,
  CONSTRAINT `usuario_esportesdeinteresse_ibfk_1`
    FOREIGN KEY (`CPF_usuario`)
    REFERENCES `pi_bbd`.`usuario` (`CPF`)
    ON DELETE CASCADE,
  CONSTRAINT `usuario_esportesdeinteresse_ibfk_2`
    FOREIGN KEY (`nome_esporte`)
    REFERENCES `pi_bbd`.`esporte` (`nome`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
